### ISSUE TITLE
Mejorar el formato del README.md

### ISSUE THREAD

**Issue by joaquinballesteros** [Jesusve99/IngSof2020#1]
El formato del readme debería ser mejorado, mirad el siguiente link (http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html para ver como formatear este documento.

**Comment by Jesusve99** [comment]
Buenas, he modificado el archivo README.md, ¿hay alguna modificación de formato más que no haya realizado?
Gracias por su tiempo.

**Comment by joaquinballesteros** [comment]
Faltaría por añadir una descipción del proyecto
